-- =====================================================================================
-- SEED SCRIPT FOR 'products' TABLE
-- =====================================================================================
-- This script populates the 'products' table with initial product data.
--
-- How to use:
-- 1. Go to your Supabase project dashboard.
-- 2. Navigate to the 'SQL Editor'.
-- 3. Copy and paste the entire content of this file into the editor.
-- 4. Click 'Run'.
--
-- This will insert all sample products into your database.

-- Empty existing data to prevent duplication if the script is run multiple times
TRUNCATE TABLE public.products RESTART IDENTITY;

-- Insert new data
INSERT INTO public.products (name, category, price, "characteristics", description, image_url) VALUES
('Carolina Reaper Chili Seeds', 'seeds', 12000, 'Pack Size: Approx. 12 seeds <br> - Quality: Premium Grade <br> - Heat Level: Extreme (2,200,000 SHU) <br> - Skill Level: Intermediate <br> - Harvest: ~90 days', 'Unleash the ultimate heat in your garden with Carolina Reaper Chili Seeds. A legendary cross between the Habanero and Ghost Pepper, this pepper holds the title for one of the world''s hottest, boasting a staggering 2.2 million Scoville Heat Units (SHU). Each pepper features a unique, wrinkled texture and a signature pointed tail. Perfect for thrill-seeking spice enthusiasts and collectors of rare chili varieties. For a successful harvest, plant in a sunny, tropical-like environment and maintain with consistent watering and balanced organic fertilizer.', 'img/general/Cabai Carolina.png'),
('Fatalii Chili Seeds', 'seeds', 12000, 'Pack Size: Approx. 12 seeds <br> - Flavor Profile: Intense Citrus & Heat <br> - Heat Level: Very Hot (125k-400k SHU) <br> - Origin: Central African Republic <br> - Harvest: ~80 days', 'Ignite your senses with Fatalii Chili Seeds, a vibrant pepper from Central Africa. This unique variety delivers a fiery, citrus-forward heat that’s perfect for creating gourmet hot sauces and adding a zesty kick to any dish. Fatalii peppers are known for their brilliant yellow color and fruity aroma, making them a standout in the garden. Thrives in sunny, warm climates and rewards growers with a quick and plentiful harvest. An excellent choice for gardeners looking to explore bold, exotic flavors.', 'img/general/Cabai Fatalii.png'),
('Ghost Pepper (Bhut Jolokia) Chili Seeds', 'seeds', 15000, 'Pack Size: Approx. 12 seeds <br> - Type: Legendary Superhot <br> - Heat Level: Extreme (1,041,427 SHU) <br> - Origin: Northeast India <br> - Harvest: ~100 days', 'Embrace the legendary fire of Ghost Pepper (Bhut Jolokia) seeds, sourced from the fields of Northeast India. Famously one of the first peppers to break the 1 million SHU barrier, its heat builds slowly before unleashing a powerful, lingering intensity. Beyond the spice, Ghost Peppers offer a subtle fruity aroma, perfect for crafting world-class hot sauces and potent chili powders. A must-grow for any serious chili aficionado seeking iconic heat.', 'img/general/Cabai Ghost Pepper.png'),
('Classic Habanero Chili Seeds', 'seeds', 10000, 'Pack Size: Approx. 12 seeds <br> - Flavor Profile: Fruity & Fiery <br> - Heat Level: Very Hot (100k-350k SHU) <br> - Origin: Caribbean <br> - Harvest: ~80 days', 'Bring a wave of tropical heat to your garden with Classic Habanero Chili Seeds. A cornerstone of Caribbean cuisine, the Habanero strikes a perfect balance between intense fire and a delicate, fruity flavor with notes of mango and papaya. Its iconic lantern shape and vibrant orange color make it a garden favorite. Ideal for creating authentic hot sauces, zesty marinades, and adding a signature kick to any meal.', 'img/general/Cabai Habanero.png'),
('Jalapeño Chili Seeds', 'seeds', 20000, 'Pack Size: Approx. 12 seeds <br> - Flavor Profile: Crisp & Mildly Spicy <br> - Heat Level: Medium (2,500-8,000 SHU) <br> - Origin: Mexico <br> - Harvest: ~75 days', 'Grow the world’s most versatile pepper with our classic Jalapeño Chili Seeds. Delivering a satisfying, moderate heat and a crisp, grassy flavor, Jalapeños are a culinary essential. Perfect for slicing fresh on nachos, stuffing for delicious poppers, or pickling for a year-round zesty treat. This reliable plant is easy to grow in containers or garden beds, producing a steady supply of dark green peppers that will ripen to a fiery red.', 'img/general/Cabai Jalapeno.png'),
('Naga Viper Chili Seeds', 'seeds', 28000, 'Pack Size: Approx. 12 seeds <br> - Type: Extreme Hybrid <br> - Heat Level: Extreme (1,382,118 SHU) <br> - Origin: United Kingdom <br> - Harvest: ~95 days', 'Push your spice tolerance to the limit with Naga Viper Chili Seeds. This formidable hybrid is a blistering cross of three legends—the Naga Morich, Bhut Jolokia, and Trinidad Scorpion. The result is a pepper with a creeping, intense heat that builds to scorching levels. Its gnarled, fiery red pods are a trophy for any chili grower. A must-have for collectors and heat seekers for a truly extreme experience.', 'img/general/Cabai Naga Viper.png'),
('Orange Drop Ornamental Chili Seeds', 'seeds', 17000, 'Pack Size: Approx. 12 seeds <br> - Type: Edible Ornamental <br> - Heat Level: Mild to Medium <br> - Feature: Highly Decorative <br> - Harvest: ~85 days', 'Add a splash of color to your home or garden with Orange Drop Ornamental Chili Seeds. This compact plant produces a stunning cascade of small, vibrant orange peppers that are as beautiful as they are tasty. With a mild, refreshing heat, they can be used to add a gentle kick to dishes or simply enjoyed for their visual appeal. Perfect for container gardening, windowsills, and balconies.', 'img/general/Cabai Orange Drop.png'),
('Scotch Bonnet Chili Seeds', 'seeds', 25000, 'Pack Size: Approx. 12 seeds <br> - Flavor Profile: Sweet & Spicy <br> - Heat Level: Very Hot (100k-350k SHU) <br> - Origin: Caribbean <br> - Harvest: ~90 days', 'Infuse your cooking with authentic Caribbean flavor with our Scotch Bonnet Chili Seeds. Instantly recognizable by its unique, tam-o''-shanter shape, this pepper is the heart and soul of Jamaican jerk seasoning. It offers a potent heat that’s beautifully balanced with sweet, fruity notes of apple and cherry. A must-have for crafting fiery hot sauces and bringing island flair to your grilling.', 'img/general/Cabai Scotch Bonnet.png'),
('Thai Bird''s Eye Chili Seeds', 'seeds', 15000, 'Pack Size: Approx. 12 seeds <br> - Flavor Profile: Clean & Intense Heat <br> - Heat Level: Hot (50k-100k SHU) <br> - Origin: Southeast Asia <br> - Harvest: ~75 days', 'Grow the essential ingredient for authentic Southeast Asian cuisine with our Thai Bird''s Eye Chili Seeds. Small in size but immense in flavor, these peppers (known as *Prik Kee Noo* in Thai) deliver a sharp, clean, and intense heat. They are the backbone of countless regional dishes, from fiery stir-fries to complex curry pastes. This hardy and productive plant is perfect for container gardening and thrives in warm climates.', 'img/general/Cabai Thai Chili.png'),
('ZA Nitrogen & Sulfur Plant Fertilizer', 'nutrition', 30000, 'Composition: Nitrogen (21%), Sulfur (24%) <br> - Type: Chemical Fertilizer <br> - Primary Use: Vegetative Growth <br> - Package Size: 1kg', 'Promote vigorous, leafy growth with our ZA Nitrogen & Sulfur Fertilizer. This potent formula delivers a targeted blend of Nitrogen (21%) and Sulfur (24%) to encourage the development of strong stems and lush, green foliage. It’s particularly effective for leafy vegetables, young plants, and lawns. A trusted choice for gardeners seeking to boost vegetative health and achieve vibrant results. Apply as directed for best performance.', 'img/general/Pupuk X.png'),
('Burnt Rice Husk Growing Medium', 'media', 7000, 'Material: Carbonized Rice Husk <br> - Key Benefit: Improves Soil Aeration <br> - Feature: Sterile & Moisture-Retentive <br> - Package Size: 1 Bag', 'Build the ideal foundation for robust root systems with our Burnt Rice Husk Growing Medium. This natural, sterile substrate is created by carbonizing rice husks, resulting in a lightweight and highly porous material. It excels at improving soil aeration, preventing compaction, and retaining moisture, which helps defend against root rot. Perfect for amending potting mixes, improving garden beds, or using as a standalone hydroponic medium.', 'img/general/Sekam Bakar.png'),
('Hydroponic Seeding Sponge', 'media', 3000, 'Application: Hydroponic Seeding <br> - Material: High-Density Sponge <br> - Key Benefit: Balanced Water Retention & Aeration <br> - Format: 1 Multi-Cell Board', 'Achieve superior germination rates for your hydroponic system with our high-density Seeding Sponges. Engineered for the perfect balance of moisture retention and aeration, these sponges provide an ideal environment for seeds to sprout while protecting delicate roots from rot. They are perfect for starting leafy greens, herbs, and other vegetables. The sponge board can be easily separated or cut to fit any net pot or tray.', 'img/general/Spons Hidroponik.png'),
('Precision Pruning Shears', 'equipment', 38000, 'Blade Material: High-Carbon Stainless Steel <br> - Cut: Sharp & Precise <br> - Handle: Ergonomic Non-Slip Grip <br> - Best For: Trimming, Shaping, Harvesting', 'Achieve clean, surgical cuts with our Precision Pruning Shears. Forged from high-carbon stainless steel, the blades are exceptionally sharp and corrosion-resistant, ensuring plant health and tool longevity. The ergonomic, non-slip handle provides comfort and control, making them ideal for delicate trimming, shaping, and harvesting. An indispensable tool for the meticulous gardener who values accuracy and quality.', 'img/general/Gunting Tanaman.png'),
('Gardening Starter Tool Set', 'promo', 75000, 'Contents: Trowel, Cultivator, Shears, Gloves <br> - Target User: Beginners <br> - Design: Ergonomic & Durable <br> - Use Case: Home Gardening Essentials', 'Start your gardening adventure with confidence using our all-in-one Gardening Starter Tool Set. This curated kit provides four essential, high-quality tools: a durable trowel, a comfortable hand cultivator, precision pruning shears, and a pair of protective gloves. Every piece is designed for ergonomic comfort and built to handle countless hours in the garden. The perfect gift for aspiring green thumbs.', 'img/general/Set Komplit.png');

-- =====================================================================================
-- SEED SCRIPT FOR 'news' TABLE
-- =====================================================================================
-- This script populates the 'news' table with initial news data.

-- Empty existing data to prevent duplication
TRUNCATE TABLE public.news RESTART IDENTITY;

-- Insert new news data
INSERT INTO public.news (title, excerpt, image_url) VALUES
('5 Essential Tips for Your First Home Hydroponics System', 'Ready to dive into the world of soil-free gardening? This guide breaks down the five most important things you need to know to start a thriving hydroponic garden at home.', 'img/Pemula.png'),
('A Beginner''s Guide to A/B Mix Hydroponic Nutrients', 'Ever wondered what A/B mix nutrients are? This article explains the science behind the two-part formula and why it’s the secret to unlocking your plants'' full potential.', 'img/Nutrisi AB.png'),
('Choosing Your Growing Medium: Rockwool vs. Coco Coir vs. Clay Pebbles', 'Rockwool, coco coir, and clay pebbles are three of the most popular hydroponic growing media. We compare their strengths and weaknesses to help you decide which one is right for your system.', 'img/Cabai Silang.png');
