-- =====================================================================================
-- SEED SCRIPT FOR 'products' TABLE
-- =====================================================================================
-- This script populates the 'products' table with initial product data.
--
-- How to use:
-- 1. Go to your Supabase project dashboard.
-- 2. Navigate to the 'SQL Editor'.
-- 3. Copy and paste the entire content of this file into the editor.
-- 4. Click 'Run'.
--
-- This will insert all sample products into your database.

-- Empty existing data to prevent duplication if the script is run multiple times
TRUNCATE TABLE public.products RESTART IDENTITY;

-- Insert new data
INSERT INTO public.products (name, category, price, "characteristics", description, image_url) VALUES
('Carolina Reaper Chili Seeds', 'seeds', 12000, '1 pack contains ±12 seeds <br> - Superior Seeds <br> - Heat Level: Very High (±2,200,000 SHU) <br> - Care: Medium <br> - Harvest Time: ±90 days', 'Unleash the ultimate heat in your garden with Carolina Reaper Chili Seeds. A legendary cross between the Habanero and Ghost Pepper, this pepper holds the title for one of the world''s hottest, boasting a staggering 2.2 million Scoville Heat Units (SHU). Each pepper features a unique, wrinkled texture and a signature pointed tail. Perfect for thrill-seeking spice enthusiasts and collectors of rare chili varieties. For a successful harvest, plant in a sunny, tropical-like environment and maintain with consistent watering and balanced organic fertilizer.', 'img/general/Cabai Carolina.png'),
('Fatalii Chili Seeds', 'seeds', 12000, '1 pack contains ±12 seeds <br> - Flavor: Spicy & Citrus <br> - Heat Level: 125,000–400,000 SHU <br> - Origin: Central Africa <br> - Harvest: Approx. 80 days', 'Discover the unique flavor of Fatalii Chili Seeds, straight from Central Africa. Known for their intense heat paired with a refreshing citrus aroma, these bright yellow peppers are perfect for crafting hot sauces, fermented chili pastes, or adding a kick to fresh dishes. This variety is easy to grow in tropical climates, offering a fast and abundant harvest. Ideal for planting in pots or directly in your garden with full sun exposure.', 'img/general/Cabai Fatalii.png'),
('Ghost Pepper (Bhut Jolokia) Chili Seeds', 'seeds', 15000, '1 pack contains ±12 seeds <br> - Type: Super Hot <br> - Heat Level: Approx. 1,041,427 SHU <br> - Origin: Northeast India <br> - Harvest: Approx. 100 days', 'Experience the legendary heat of Ghost Pepper (Bhut Jolokia) seeds, originating from Assam, India. Once crowned the world''s hottest pepper, it delivers a slow-building but intensely long-lasting heat, exceeding 1 million SHU. Its vibrant red fruit carries a distinctive tropical fruit aroma, making it ideal for creating super-hot sauces and chili powders. Thrives in warm climates with full sun.', 'img/general/Cabai Ghost Pepper.png'),
('Classic Habanero Chili Seeds', 'seeds', 10000, '1 pack contains ±12 seeds <br> - Flavor: Tropical & Spicy <br> - Heat Level: 100,000–350,000 SHU <br> - Color: Orange/Red <br> - Harvest: Approx. 80 days', 'Add a taste of the tropics to your garden with our Classic Habanero Chili Seeds from Mexico and the Caribbean. Famous for a sharp, intense heat balanced by notes of mango and papaya, these small, bright orange peppers are a go-to for hot sauces and zesty dishes. They grow best in warm temperatures with regular watering and well-drained soil.', 'img/general/Cabai Habanero.png'),
('Jalapeño Chili Seeds', 'seeds', 20000, '1 pack contains ±12 seeds <br> - Heat: Medium <br> - Heat Level: 2,500–8,000 SHU <br> - Origin: Mexico <br> - Harvest: Approx. 75 days', 'Grow the iconic Jalapeño pepper, a staple in Mexican cuisine and beyond. These seeds produce peppers with a satisfying medium heat and a fresh, bright flavor, perfect for slicing onto pizza, stuffing for appetizers, or dicing into tacos. The fruits mature from dark green to red and are easy to grow in pots or small gardens, offering an abundant and reliable harvest.', 'img/general/Cabai Jalapeno.png'),
('Naga Viper Chili Seeds', 'seeds', 28000, '1 pack contains ±12 seeds <br> - Type: Super Hybrid <br> - Heat Level: Approx. 1,382,118 SHU <br> - Origin: England <br> - Harvest: Approx. 95 days', 'Challenge your limits with Naga Viper Chili Seeds, a blistering hybrid of three legendary peppers: Naga Morich, Bhut Jolokia, and Trinidad Scorpion. This variety is known for its exceptionally high heat level that builds gradually. The dark red, wrinkled peppers are a must-have for serious chili collectors and extreme spice enthusiasts. Grows best in warm climates with full sun.', 'img/general/Cabai Naga Viper.png'),
('Ornamental Orange Drop Chili Seeds', 'seeds', 17000, '1 pack contains ±12 seeds <br> - Type: Mini Chili <br> - Color: Bright Orange <br> - Flavor: Refreshing Heat <br> - Harvest: Approx. 85 days', 'Brighten up your space with Orange Drop Chili Seeds, which produce beautiful, bright orange mini chilies. Offering a mild to medium heat with a fresh aroma, this variety is as much an ornamental plant as it is a culinary ingredient. Its compact and productive nature makes it perfect for growing in decorative pots on a terrace or balcony.', 'img/general/Cabai Orange Drop.png'),
('Scotch Bonnet Chili Seeds', 'seeds', 25000, '1 pack contains ±12 seeds <br> - Flavor: Tropical Heat <br> - Heat Level: 100,000–350,000 SHU <br> - Origin: Caribbean <br> - Harvest: Approx. 90 days', 'Bring Caribbean flavor to your kitchen with Scotch Bonnet Chili Seeds. A staple in Jamaican cuisine, this pepper is shaped like a classic bonnet and ripens from yellow to a vibrant red. It delivers a sharp heat balanced by sweet, tropical notes of pineapple and mango. Ideal for authentic hot sauces, grilled dishes, and classic Caribbean jerk marinades.', 'img/general/Cabai Scotch Bonnet.png'),
('Thai "Bird''s Eye" Chili Seeds', 'seeds', 15000, '1 pack contains ±12 seeds <br> - Heat: Sharp & Intense <br> - Heat Level: 50,000–100,000 SHU <br> - Size: Small <br> - Harvest: Approx. 75 days', 'Grow the essential ingredient for authentic Southeast Asian cuisine with Thai ''Bird''s Eye'' Chili Seeds (Prik Kee Noo). These small but mighty peppers pack a sharp, intense heat and a fresh aroma, perfect for stir-fries, chili pastes, and spicy soups. This variety is highly productive, heat-resistant, and easy to care for, thriving in both pots and garden beds.', 'img/general/Cabai Thai Chili.png'),
('ZA Nitrogen & Sulfur Fertilizer', 'nutrition', 30000, 'Nutrient Source: Nitrogen (21%) & Sulfur (24%) <br> - Type: Non-Organic <br> - Use: Stimulates Leaf & Stem Growth <br> - Size: 1kg', 'Boost the vegetative growth of your plants with ZA (Zwavelzure Ammoniak) Fertilizer. This chemical fertilizer provides a powerful combination of Nitrogen (21%) and Sulfur (24%), essential for promoting lush, healthy leaves and stems. Excellent for leafy vegetables, rice, and ornamental plants. Apply in measured doses to ensure optimal results.', 'img/general/Pupuk X.png'),
('Burnt Rice Husk Growing Medium', 'media', 7000, 'Type: Growing Medium <br> - Porosity: High <br> - Benefit: Sterile & Improves Aeration <br> - Size: 1 bag', 'Create the perfect foundation for healthy roots with our Burnt Rice Husk growing medium. This all-natural, sterile material is produced by partially burning rice husks, resulting in a highly porous substrate. It helps retain moisture while improving air circulation, preventing root rot and promoting vigorous growth. Ideal for amending soil mixtures or for use in hydroponic systems.', 'img/general/Sekam Bakar.png'),
('Hydroponic Seeding Sponge', 'media', 3000, 'Use: Seeding Medium <br> - System: Hydroponics <br> - Benefit: High Water Absorption <br> - Size: 1 Board', 'Start your hydroponic garden successfully with our specialized Seeding Sponge. Designed for optimal water absorption, it keeps seeds moist while maintaining excellent root aeration to prevent rot. Perfect for germinating leafy greens like lettuce, spinach, and kale. The board can be easily cut to fit any size of net pot or seeding tray.', 'img/general/Spons Hidroponik.png'),
('Precision Pruning Shears', 'equipment', 38000, 'Material: Stainless Steel <br> - Quality: Sharp & Precise <br> - Design: Ergonomic <br> - Feature: Rustproof', 'Maintain your garden with our high-quality Precision Pruning Shears. Made from sharp, durable stainless steel, these shears deliver clean and precise cuts every time. The ergonomic handle ensures comfort during use, making them perfect for trimming small branches, shaping plants, and harvesting herbs or flowers. An essential tool for any gardener.', 'img/general/Gunting Tanaman.png'),
('Beginner''s Gardening Tool Set', 'promo', 75000, 'Complete Set <br> - Includes: Trowel, Gloves, Shears, & Cultivator <br> - Material: Durable & High-Quality <br> - Perfect for Beginners', 'Get everything you need to start your gardening journey with our complete tool set. This kit includes essential, high-quality tools: a mini trowel, protective gloves, precision shears, and a hand cultivator. Each tool features an ergonomic design for comfort and is built to last. Ideal for new gardeners starting a home garden.', 'img/general/Set Komplit.png');

-- =====================================================================================
-- SEED SCRIPT FOR 'news' TABLE
-- =====================================================================================
-- This script populates the 'news' table with initial news data.

-- Empty existing data to prevent duplication
TRUNCATE TABLE public.news RESTART IDENTITY;

-- Insert new news data
INSERT INTO public.news (title, excerpt, image_url) VALUES
('5 Essential Tips for Starting Your First Home Hydroponics System', 'Hydroponics doesn''t have to be complicated. With this beginner''s guide, you can easily start your own mini hydroponic garden on a balcony or in your backyard.', 'img/Pemula.png'),
('Understanding A/B Mix Nutrients: The Key to Healthy Hydroponic Plants', 'What is an A/B mix nutrient solution and why is it so important for hydroponics? Learn how to properly mix and apply it to achieve maximum growth and harvest.', 'img/Nutrisi AB.png'),
('Choosing a Growing Medium: Rockwool vs. Cocopeat vs. Hydroton', 'Every hydroponic growing medium has unique advantages. This guide compares the most popular options to help you choose the best fit for your plants and system.', 'img/Cabai Silang.png');
