-- =====================================================================================
-- PERBAIKAN SKEMA PENTING (JALANKAN INI DI EDITOR SQL SUPABASE ANDA)
-- =====================================================================================
-- Perintah berikut memperbaiki relasi antara tabel 'orders' dan 'profiles'.
-- Ini akan menyelesaikan error "Could not find a relationship" di halaman admin.

-- 1. Hapus foreign key lama (yang menunjuk ke auth.users)
-- CATATAN: Nama constraint bisa berbeda di database Anda.
ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_user_id_fkey;

-- 2. Tambahkan foreign key baru yang menunjuk ke public.profiles(id)
ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_fkey 
FOREIGN KEY (user_id) REFERENCES public.profiles(id);

-- =====================================================================================
-- SKEMA LENGKAP UNTUK REFERENSI
-- =====================================================================================

-- Membuat tabel 'orders' untuk menyimpan data pesanan.
-- Sudah menggunakan foreign key ke profiles(id), menambahkan kolom 'notes',
-- dan default status 'Proses Admin'.
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    order_code TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    order_details JSONB NOT NULL,
    shipping_address JSONB NOT NULL,
    total_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'Proses Admin'::text NOT NULL,
    shipping_receipt TEXT,
    notes TEXT
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 3. Kebijakan RLS untuk pengguna biasa
CREATE POLICY "Allow users to view their own orders"
ON public.orders
FOR SELECT
USING (auth.uid() = user_id);

CREATE POLICY "Allow users to create their own orders"
ON public.orders
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 4. Infrastruktur & kebijakan untuk admin
CREATE TABLE IF NOT EXISTS public.admins (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id)
);

CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.admins WHERE user_id = auth.uid()
  );
$$ LANGUAGE sql SECURITY DEFINER;

CREATE POLICY "Allow admin full access"
ON public.orders
FOR ALL
USING (is_admin())
WITH CHECK (is_admin());

-- 5. Supabase Realtime setup
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE schemaname = 'public' AND tablename = 'orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
  END IF;
END $$;
