-- =====================================================================================
-- PERBAIKAN SKEMA PENTING (JALANKAN INI DI EDITOR SQL SUPABASE ANDA)
-- =====================================================================================
-- Perintah berikut akan memperbaiki relasi antara tabel 'orders' dan 'profiles'.
-- Ini akan menyelesaikan error "Could not find a relationship" di halaman admin.

-- 1. Hapus foreign key yang lama (yang menunjuk ke auth.users)
-- CATATAN: Nama constraint 'orders_user_id_fkey' mungkin berbeda di database Anda.
-- Jika perintah ini gagal, cari nama yang benar di bawah "Database" -> "Table Editor" ->
-- pilih tabel 'orders' dan lihat di bawah "Constraints".
ALTER TABLE public.orders DROP CONSTRAINT orders_user_id_fkey;

-- 2. Tambahkan foreign key baru yang menunjuk ke public.profiles(id)
-- Ini akan membuat relasi yang dibutuhkan oleh query di halaman admin.
ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_fkey FOREIGN KEY (user_id) REFERENCES public.profiles(id);

-- =====================================================================================
-- SKEMA LENGKAP (UNTUK REFERENSI)
-- =====================================================================================

-- Skema ini mendefinisikan tabel dan kebijakan keamanan untuk sistem pesanan.

-- 1. Membuat tabel 'orders' untuk menyimpan data pesanan
-- Perintah CREATE TABLE ini telah diperbarui untuk menggunakan foreign key yang benar.
CREATE TABLE public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    -- user_id sekarang mereferensikan profiles(id) untuk memungkinkan join yang mudah.
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    order_code TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    order_details JSONB NOT NULL,
    shipping_address JSONB NOT NULL,
    total_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'Proses Admin'::text NOT NULL,
    shipping_receipt TEXT,
    notes TEXT
);

-- 2. Mengaktifkan Row Level Security (RLS) untuk keamanan
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 3. Membuat kebijakan RLS untuk pengguna biasa
-- Kebijakan ini memastikan pengguna hanya bisa mengakses data mereka sendiri.

-- Kebijakan RLS: Pengguna hanya bisa melihat pesanan mereka sendiri
CREATE POLICY "Allow users to view their own orders"
ON public.orders
FOR SELECT
USING (auth.uid() = user_id);

-- Kebijakan RLS: Pengguna hanya bisa membuat pesanan untuk diri mereka sendiri
CREATE POLICY "Allow users to create their own orders"
ON public.orders
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 4. Membuat infrastruktur dan kebijakan untuk peran Admin
-- Ini memungkinkan admin untuk mengelola semua pesanan dari semua pengguna.

-- Membuat tabel untuk menyimpan user ID admin.
-- Untuk menjadikan pengguna sebagai admin, tambahkan UUID mereka ke tabel ini.
CREATE TABLE IF NOT EXISTS public.admins (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id)
);

-- Membuat fungsi SQL untuk memeriksa apakah pengguna saat ini adalah admin.
-- Fungsi ini akan mengembalikan 'true' jika ID pengguna ada di tabel 'admins'.
CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.admins WHERE user_id = auth.uid()
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- Membuat kebijakan RLS untuk admin.
-- Kebijakan ini memberikan akses penuh (SELECT, INSERT, UPDATE, DELETE) ke tabel 'orders'
-- jika fungsi is_admin() mengembalikan 'true'.
CREATE POLICY "Allow admin full access" ON public.orders
FOR ALL USING (is_admin()) WITH CHECK (is_admin());

-- 5. Menyiapkan Supabase Realtime untuk tabel 'orders'
-- Ini memungkinkan pembaruan data secara real-time di frontend.
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE schemaname = 'public' AND tablename = 'orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
  END IF;
END $$;
