-- =====================================================================================
-- PERBAIKAN SKEMA PENTING (JALANKAN INI DI EDITOR SQL SUPABASE ANDA)
-- =====================================================================================
-- Perintah berikut memperbaiki relasi antara tabel 'orders' dan 'profiles'.
-- Ini akan menyelesaikan error "Could not find a relationship" di halaman admin.

-- =====================================================================================
-- KRITIS: Pastikan user bisa update data alamatnya sendiri di tabel profiles
-- =====================================================================================
ALTER TABLE IF EXISTS public.profiles ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Users can view their own profile" ON public.profiles;
CREATE POLICY "Users can view their own profile"
ON public.profiles
FOR SELECT
USING (auth.uid() = id);

DROP POLICY IF EXISTS "Users can update their own data" ON public.profiles;
CREATE POLICY "Users can update their own data"
ON public.profiles
FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);

DROP POLICY IF EXISTS "Users can insert their own profile" ON public.profiles;
CREATE POLICY "Users can insert their own profile"
ON public.profiles
FOR INSERT
WITH CHECK (auth.uid() = id);

-- 1. Hapus foreign key lama (yang menunjuk ke auth.users)
-- CATATAN: Nama constraint bisa berbeda di database Anda.
ALTER TABLE public.orders DROP CONSTRAINT IF EXISTS orders_user_id_fkey;

-- 2. Tambahkan foreign key baru yang menunjuk ke public.profiles(id)
ALTER TABLE public.orders ADD CONSTRAINT orders_user_id_fkey 
FOREIGN KEY (user_id) REFERENCES public.profiles(id);

-- =====================================================================================
-- SKEMA LENGKAP UNTUK REFERENSI
-- =====================================================================================

-- Membuat tabel 'orders' untuk menyimpan data pesanan.
-- Sudah menggunakan foreign key ke profiles(id), menambahkan kolom 'notes',
-- dan default status 'Proses Admin'.
CREATE TABLE IF NOT EXISTS public.orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id UUID REFERENCES public.profiles(id) NOT NULL,
    order_code TEXT UNIQUE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    order_details JSONB NOT NULL,
    shipping_address JSONB NOT NULL,
    total_amount NUMERIC NOT NULL,
    status TEXT DEFAULT 'Proses Admin'::text NOT NULL,
    shipping_receipt TEXT,
    notes TEXT
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.orders ENABLE ROW LEVEL SECURITY;

-- 3. Kebijakan RLS untuk pengguna biasa
DROP POLICY IF EXISTS "Allow users to view their own orders" ON public.orders;
CREATE POLICY "Allow users to view their own orders"
ON public.orders
FOR SELECT
USING (auth.uid() = user_id);

DROP POLICY IF EXISTS "Allow users to create their own orders" ON public.orders;
CREATE POLICY "Allow users to create their own orders"
ON public.orders
FOR INSERT
WITH CHECK (auth.uid() = user_id);

-- 4. Infrastruktur & kebijakan untuk admin
CREATE TABLE IF NOT EXISTS public.admins (
  user_id uuid PRIMARY KEY REFERENCES auth.users(id)
);

CREATE OR REPLACE FUNCTION is_admin()
RETURNS boolean AS $$
  SELECT EXISTS (
    SELECT 1 FROM public.admins WHERE user_id = auth.uid()
  );
$$ LANGUAGE sql SECURITY DEFINER;

-- Hapus kebijakan "FOR ALL" yang lama dan ambigu
DROP POLICY IF EXISTS "Allow admin full access" ON public.orders;

-- Kebijakan baru yang lebih eksplisit untuk admin
DROP POLICY IF EXISTS "Allow admin to view all orders" ON public.orders;
CREATE POLICY "Allow admin to view all orders"
ON public.orders
FOR SELECT USING (is_admin());

DROP POLICY IF EXISTS "Allow admin to update orders" ON public.orders;
CREATE POLICY "Allow admin to update orders"
ON public.orders
FOR UPDATE USING (is_admin()) WITH CHECK (is_admin());

DROP POLICY IF EXISTS "Allow admin to delete orders" ON public.orders;
CREATE POLICY "Allow admin to delete orders"
ON public.orders
FOR DELETE USING (is_admin());

-- 5. Supabase Realtime setup
DO $$
BEGIN
  IF NOT EXISTS (
    SELECT 1
    FROM pg_publication_tables
    WHERE schemaname = 'public' AND tablename = 'orders'
  ) THEN
    ALTER PUBLICATION supabase_realtime ADD TABLE public.orders;
  END IF;
END $$;

-- =====================================================================================
-- SKEMA BARU: TABEL PRODUK
-- =====================================================================================

-- CATATAN PENTING:
-- Setelah tabel 'products' dibuat, Anda perlu mengisinya dengan data awal.
-- Buka file 'supabase_seed.sql', salin kontennya, dan jalankan di SQL Editor
-- untuk menambahkan produk contoh ke database Anda.

-- 1. Membuat tabel 'products' untuk menyimpan data produk
CREATE TABLE IF NOT EXISTS public.products (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    name TEXT NOT NULL,
    category TEXT,
    price NUMERIC NOT NULL,
    characteristics TEXT,
    description TEXT,
    image_url TEXT,
    variants JSONB DEFAULT NULL,
    discount_percent INTEGER DEFAULT NULL,
    discount_price NUMERIC DEFAULT NULL,
    weight INTEGER DEFAULT 0
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.products ENABLE ROW LEVEL SECURITY;

-- 3. Kebijakan RLS untuk Produk
-- a. Izinkan semua pengguna (termasuk anonim) untuk melihat produk
DROP POLICY IF EXISTS "Allow public read access to products" ON public.products;
CREATE POLICY "Allow public read access to products"
ON public.products
FOR SELECT
USING (true);

-- b. Izinkan admin untuk melakukan semua operasi (SELECT, INSERT, UPDATE, DELETE)
DROP POLICY IF EXISTS "Allow admin full access to products" ON public.products;
CREATE POLICY "Allow admin full access to products"
ON public.products
FOR ALL
USING (is_admin())
WITH CHECK (is_admin());

-- 4. Membuat Supabase Storage Bucket untuk gambar produk
-- Pastikan bucket 'product-images' dibuat di dashboard Supabase Anda
-- dengan akses publik.
-- (Ini adalah komentar, tindakan sebenarnya dilakukan di UI Supabase)


-- =====================================================================================
-- SKEMA BARU: TABEL NEWS
-- =====================================================================================

-- 1. Membuat tabel 'news' untuk menyimpan data berita
CREATE TABLE IF NOT EXISTS public.news (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL,
    title TEXT NOT NULL,
    excerpt TEXT,
    content TEXT,
    image_url TEXT
);

-- 2. Aktifkan Row Level Security (RLS)
ALTER TABLE public.news ENABLE ROW LEVEL SECURITY;

-- 3. Kebijakan RLS untuk News
-- a. Izinkan semua pengguna (termasuk anonim) untuk melihat berita
DROP POLICY IF EXISTS "Allow public read access to news" ON public.news;
CREATE POLICY "Allow public read access to news"
ON public.news
FOR SELECT
USING (true);

-- b. Izinkan admin untuk melakukan semua operasi (SELECT, INSERT, UPDATE, DELETE)
DROP POLICY IF EXISTS "Allow admin full access to news" ON public.news;
CREATE POLICY "Allow admin full access to news"
ON public.news
FOR ALL
USING (is_admin())
WITH CHECK (is_admin());

-- =====================================================================================
-- RPC: PROFILE UPDATE TANPA HTTP PATCH (gunakan POST /rpc/update_profile)
-- =====================================================================================

CREATE OR REPLACE FUNCTION public.update_profile(
    user_id uuid,
    full_name text DEFAULT NULL,
    phone_number text DEFAULT NULL,
    address text DEFAULT NULL
)
RETURNS TABLE (
    id uuid,
    full_name text,
    phone_number text,
    address text,
    postal_code text,
    province text,
    regency text,
    district text,
    village text,
    latitude double precision,
    longitude double precision,
    updated_at timestamptz
)
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
BEGIN
    IF auth.uid() IS NULL THEN
        RAISE EXCEPTION 'Not authenticated';
    END IF;

    IF auth.uid() <> user_id THEN
        RAISE EXCEPTION 'You can only update your own profile';
    END IF;

    RETURN QUERY
    UPDATE public.profiles p
    SET
        full_name = COALESCE(update_profile.full_name, p.full_name),
        phone_number = COALESCE(update_profile.phone_number, p.phone_number),
        address = COALESCE(update_profile.address, p.address),
        updated_at = timezone('utc'::text, now())
    WHERE p.id = user_id
    RETURNING
        p.id,
        p.full_name,
        p.phone_number,
        p.address,
        p.postal_code,
        p.province,
        p.regency,
        p.district,
        p.village,
        p.latitude,
        p.longitude,
        p.updated_at;
END;
$$;

REVOKE ALL ON FUNCTION public.update_profile(uuid, text, text, text) FROM PUBLIC;
GRANT EXECUTE ON FUNCTION public.update_profile(uuid, text, text, text) TO authenticated;

-- Kebijakan RLS spesifik update profil sendiri (id = auth.uid())
DROP POLICY IF EXISTS "profiles_update_own" ON public.profiles;
CREATE POLICY "profiles_update_own"
ON public.profiles
FOR UPDATE
USING (auth.uid() = id)
WITH CHECK (auth.uid() = id);
